CREATE DATABASE TERMITE_WEBSTORE_DB;
USE TERMITE_WEBSTORE_DB;

CREATE SCHEMA WEBSTORE_SCHEMA;
USE SCHEMA WEBSTORE_SCHEMA;

CREATE TABLE WEBSTORE_CUSTOMERS_DATA (RAW_JSON VARIANT);
-- INSERT INTO WEBSTORE_CUSTOMERS_DATA (RAW_JSON)
-- SELECT PARSE_JSON($1);

CREATE TABLE WEBSTORE_ORDERS_DATA (RAW_JSON VARIANT);
-- INSERT INTO WEBSTORE_ORDERS_DATA (RAW_JSON)
-- SELECT PARSE_JSON($1);

CREATE OR ALTER FILE FORMAT WEBSTORE_CUSTOMERS_FILE
TYPE = JSON
COMMENT = '<LOAD SOME DATA FROM JSON FILES>';

CREATE OR ALTER FILE FORMAT WEBSTORE_ORDERS_FILE
TYPE = JSON
COMMENT = '<LOAD CUSTOMERS DATA FROM A JSON FILE>';

SELECT * FROM "TERMITE_WEBSTORE_DB"."WEBSTORE_SCHEMA"."WEBSTORE_CUSTOMERS_DATA"
LIMIT 10;

SELECT * FROM "TERMITE_WEBSTORE_DB"."WEBSTORE_SCHEMA"."WEBSTORE_ORDERS_DATA"
LIMIT 10;

-- DROP TABLE WEBSTORE_CUSTOMERS_DATA;
-- DROP TABLE WEBSTORE_ORDERS_DATA;
-- DROP FILE FORMAT WEBSTORE_CUSTOMERS_FILE;
-- DROP FILE FORMAT WEBSTORE_ORDERS_FILE;